# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'about',   url: 'about.html'}
- {name: 'learning', url: 'learning.html'}
- {name: 'books', url: 'books.html'}
- {name: 'research', url: 'research.html'}
- {name: 'questions', url: 'questions.html'}
- {name: 'contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/anannabiswas'}
- {icon: 'twitter',    link: 'https://twitter.com/anannabiswas_bd'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/ananna0pi/'}
- {icon: 'envelope',   link: 'mailto:ananna314.bd@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
